# Generated by Django 5.2.14 on 2026-05-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_key', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to='accounts.clientprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['metric_key', 'period_start', 'period_end'], name='reporting_k_metric__736170_idx')],
            },
        ),
    ]
