# Generated by Django 5.2.14 on 2026-05-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhlContactMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ghl_contact_id', models.CharField(max_length=128, unique=True)),
                ('location_id', models.CharField(blank=True, max_length=128)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ghl_mapping', to='accounts.clientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
